services:
  database:
    image: mariadb:latest
    user: "1000:1000"
    container_name: rplaceclicker_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: rplacedb
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
