services:
  database:
    image: mariadb:latest
    container_name: rplaceclicker_db
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - rplace_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  server:
    image: eclipse-temurin:17-jre-jammy
    container_name: rplaceclicker_serv
    env_file: .env
    ports:
      - "8081:8080"
    volumes:
      - ./rplaceserv/target/m1dwa-server-0.2.0.jar:/app/app.jar
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MariaDBDialect
      - APP_JWT_SECRET=${JWT_SECRET}
      - APP_JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      database:
        condition: service_healthy
    entrypoint: ["java", "-jar", "app.jar"]

volumes:
  rplace_db_data:
