# Database configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/rplacedb
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server configuration
server.port=8080

# Logging configuration (Test Logger)
logging.level.root=INFO
logging.level.com.example.m1dwa=DEBUG
logging.file.name=logs/test-logger.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
