name: GitLab auto Push

on:
  push:
    branches: main 
    tags: [ '*' ] 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (GitHub)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to GitLab
        run: |
          git config --global credential.helper store
          echo "https://oauth2:${{ secrets.GITLAB_TOKEN }}@git.univ-pau.fr/tcharrier004/rplaceclicker_dev_web_2026.git" > ~/.git-credentials
          git remote add gitlab https://git.univ-pau.fr/tcharrier004/rplaceclicker_dev_web_2026.git
          git push gitlab --all
          git push gitlab --tags
        env:
          GIT_ASKPASS: /bin/echo
